GoldenblockAdmin/Controllers/AuthenticationController.cs
using Goldenblock.Common;
using Goldenblock.Common.Paging;
using Goldenblock.Entities.Contract;
using Goldenblock.Entities.V1;
using Goldenblock.Services.Contract;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Goldenblock.Controllers
{    
    public class AuthenticationController : Controller
    {
        //private readonly abstractadminservices abstractadminservices;
        //public authenticationcontroller(abstractadminservices abstractadminservices)
        //{
        //    this.abstractadminservices = abstractadminservices;
        //}


        #region Methods
        public ActionResult EmailVerification()
        {
            return View();
        }

        public ActionResult ResetPassword()
        {
            return View();
        }

        public ActionResult SignIn()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            return View();
        }
        #endregion


        //[HttpPost]
        //public JsonResult AdminLogin(string Email, string Password)
        //{
        //    var result = abstractAdminServices.Admin_Login(Email, Password);
        //    if (result.Code == 200 && result.Item != null)
        //    {
        //        Session.Clear();
        //        ProjectSession.AdminId = result.Item.Id;
        //        HttpCookie cookie = new HttpCookie("AdminLogin");
        //        cookie.Values.Add("Id", result.Item.Id.ToString());

        //        cookie.Expires = DateTime.Now.AddDays(30);
        //        Response.Cookies.Add(cookie);
        //    }
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}
    }
}

GoldenblockAdmin/Controllers/InvestmentProductManagementController.cs
using Goldenblock.Common;
using Goldenblock.Common.Paging;
using Goldenblock.Entities.Contract;
using Goldenblock.Entities.V1;
using Goldenblock.Services.Contract;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static GoldenblockAdmin.MvcApplication;

namespace Goldenblock.Controllers
{
    public class InvestmentProductManagementController : Controller
    {
        private readonly AbstractLookupConstructionPeriodServices abstractLookupConstructionPeriodServices;
        private readonly AbstractLookupReferenceDateServices abstractLookupReferenceDateServices;
        private readonly AbstractPropertyServices abstractPropertyServices;
        public InvestmentProductManagementController(AbstractLookupConstructionPeriodServices abstractLookupConstructionPeriodServices, AbstractLookupReferenceDateServices abstractLookupReferenceDateServices, AbstractPropertyServices abstractPropertyServices)
        {
            this.abstractLookupConstructionPeriodServices = abstractLookupConstructionPeriodServices;
            this.abstractLookupReferenceDateServices = abstractLookupReferenceDateServices;
            this.abstractPropertyServices = abstractPropertyServices;
        }


        #region Methods
        [NoDirectAccess]
        public ActionResult ProductInquiry()
        {
            return View();
        }

        [NoDirectAccess]
        public ActionResult InvestmentAttractionList()
        {
            return View();
        }

        public ActionResult UploadProperty()
        {
            ViewBag.ConstructionPeriod = BindConstructionPeriodDrp();
            ViewBag.ReferenceDate = BindReferenceDatedDrp();           
            return View();
        }             
            
        public ActionResult PropertyEdit(string PropertyId = "")
        {
            ViewBag.ConstructionPeriod = BindConstructionPeriodDrp();
            ViewBag.ReferenceDate = BindReferenceDatedDrp();
            ViewBag.PropertyId = ConvertTo.Integer(ConvertTo.Base64Decode(PropertyId));
            var result = abstractPropertyServices.Property_ById(ViewBag.PropertyId);
            return View(result.Item);
        }

        public ActionResult PropertyDetails()
        {
            return View();
        }
        #endregion

        public IList<SelectListItem> BindConstructionPeriodDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;

                
                var models = abstractLookupConstructionPeriodServices.LookupConstructionPeriod_All(pageParam, ""); 

                foreach (var master in models.Values)
                {
                    items.Add(new SelectListItem() { Text = master.Name.ToString(), Value = Convert.ToString(master.Id) });
                }
                return items;
            }
            catch (Exception e)
            {
                return items;
            }
        }

        public IList<SelectListItem> BindReferenceDatedDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;


                var models = abstractLookupReferenceDateServices.LookupReferenceDate_All(pageParam, "");

                foreach (var master in models.Values)
                {
                    items.Add(new SelectListItem() { Text = master.Name.ToString(), Value = Convert.ToString(master.Id) });
                }
                return items;
            }
            catch (Exception e)
            {
                return items;
            }
        }

        [HttpPost]
        public JsonResult GetProperty(int Id)
        {
            var result = abstractPropertyServices.Property_ById(Id);            
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddProperty(Property property)
        {  
            var result = abstractPropertyServices.Property_Upsert(property);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

GoldenblockAdmin/Controllers/MemberManagementController.cs
using Goldenblock.Common;
using Goldenblock.Entities.Contract;
using Goldenblock.Entities.V1;
using Goldenblock.Services.Contract;
using System;
using System.Web;
using System.Web.Mvc;

namespace Goldenblock.Controllers
{
    public class MemberManagementController : Controller
    {
        
        #region Methods
        public ActionResult CoinDepositAndWithdrawal()
        {
            return View();
        }
        public ActionResult CoinStaking()
        {
            return View();
        }
        public ActionResult CoinTransactionHistory()
        {
            return View();
        }
        public ActionResult UserProfile()
        {
            return View();
        }
        public ActionResult UploadProperty()
        {
            return View();
        }
        public ActionResult UserInfo()
        {
            return View();
        }
        #endregion
    }
}

GoldenblockAdmin/Controllers/NoticeManagementController.cs
using Goldenblock.Common;
using Goldenblock.Entities.Contract;
using Goldenblock.Entities.V1;
using Goldenblock.Services.Contract;
using System;
using System.Web;
using System.Web.Mvc;

namespace Goldenblock.Controllers
{
    public class NoticeManagementController : Controller
    {
        
        #region Methods
        public ActionResult Event()
        {
            return View();
        }
        public ActionResult EventDetails()
        {
            return View();
        }
        public ActionResult EventDetailsEdit()
        {
            return View();
        }
        public ActionResult Notice()
        {
            return View();
        }
        public ActionResult NoticeAdd()
        {
            return View();
        }
        public ActionResult NoticeDetails()
        {
            return View();
        }
        public ActionResult NoticeDetailsEdit()
        {
            return View();
        }
        public ActionResult Terms()
        {
            return View();
        }
        public ActionResult TermsAdd()
        {
            return View();
        }
        public ActionResult TermsDetails()
        {
            return View();
        }
        public ActionResult TermsDetailsEdit()
        {
            return View();
        }
        #endregion
    }
}

GoldenblockAdmin/Views/Authentication/ResetPassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Reset password | Gloden Block</title>

    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2f1e1c">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheets -->
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/assets/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.css" />



    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/assets/css/main.min.css">


</head>

<body>

    <div class="d-flex align-items-center min-vh-100">
        <form class="form-signin">


            <label for="inputEmail" class="sr-only">비밀번호 숫자 6자리를 입력해 주세요.</label>
            <input type="password" id="inputEmail" class="form-control control-dark rounded border" placeholder="비밀번호 숫자 6자리를 입력해 주세요." required autofocus>

            <label for="inputEmail" class="sr-only">다시한번 입력해 주세요.</label>
            <input type="password" id="inputEmail" class="form-control control-dark rounded border" placeholder="다시한번 입력해 주세요." required autofocus>




            <a href="@Url.Action("ProductInquiry","InvestmentProductManagement")" class="btn btn-lg btn-primary btn-block mt-5" type="submit">로그인</a>

            <div class="d-flex mt-3 justify-content-between">
                <a href="@Url.Action("SignIn","Authentication")">로그인</a>
            </div>
        </form>
    </div>


    <!-- Scripts -->
    <script src="~/assets/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/assets/vendors/slick-carousel/slick/slick.min.js"></script>
    <script src="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.js"></script>


    <!-- Main Js -->
    <script src="~/assets/js/main.min.js"></script>
</body>

</html>

GoldenblockAdmin/Views/Authentication/SignIn.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signin | Gloden Block</title>

    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2f1e1c">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheets -->
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/assets/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.css" />



    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/assets/css/main.min.css">


</head>

<body>

    <div class="d-flex align-items-center min-vh-100">
        <form class="form-signin">

            <h1 class="h3 mb-4 font-weight-normal">please log in</h1>


            <label for="inputEmail" class="sr-only">Email</label>
            <input type="email" id="email" class="form-control control-dark border" placeholder="e-mail" required autofocus>


            <label for="inputPassword" class="sr-only">password</label>
            <input type="password" id="password" class="form-control control-dark border" placeholder="password" required>

            <a href="javascript:;" class="btn btn-lg btn-primary btn-block mt-5" onclick="login();">Log in</a>

            <div class="d-flex mt-3 justify-content-between">
                <a href="@Url.Action("SignUp","Authentication")">회원가입</a>
                <a href="@Url.Action("ResetPassword","Authentication")">비밀번호 찾기</a>
            </div>
        </form>
    </div>


    <!-- Scripts -->
    <script src="~/assets/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/assets/vendors/slick-carousel/slick/slick.min.js"></script>
    <script src="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.js"></script>


    <!-- Main Js -->
    <script src="~/assets/js/main.min.js"></script>

    <script>
        function login() {
              $.ajax({
                            url: '@Url.Action("AdminLogin", "Authentication")',
                            data: { email: $("#email").val(), password: $("#password").val() },
                            type: "POST",
                            dataType: "json",
                            success: function (result) {
                                if (result.Code == 200) {
                                    alert(result.Message);
                                    window.location.href = '@Url.Action("ProductInquiry", "InvestmentProductManagement")';
                                } else {
                                    alert(result.Message);
                                }
                            },
                  error: function (result) {
                      alert("Something was wrong!!");
                            }
                        });
        }
    </script>
</body>

</html>

GoldenblockAdmin/Views/Authentication/SignUp.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signup | Gloden Block</title>

    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2f1e1c">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheets -->
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="~/assets/vendors/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="~/assets/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/assets/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.css" />



    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/assets/css/main.min.css">


</head>

<body>

    <div class="d-flex align-items-center min-vh-100">
        <form class="form-signin">

            <h1 class="h3 mb-4 font-weight-normal">서비스 가입을 위해 이메일을 등록해 주세요.</h1>


            <label for="inputEmail" class="sr-only">이메일</label>
            <input type="email" id="inputEmail" class="form-control control-dark border" placeholder="이메일" required autofocus>


            <a href="~/assets/signup-2.html" class="btn btn-lg btn-primary btn-block mt-5" type="submit">인증번호 전송</a>

            <div class="d-flex mt-3 justify-content-between">
                <a href="@Url.Action("SignIn","Authentication")" >로그인</a>
            </div>
        </form>
    </div>


    <!-- Scripts -->
    <script src="~/assets/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/assets/vendors/slick-carousel/slick/slick.min.js"></script>
    <script src="~/assets/vendors/fancyapps/fancybox/dist/jquery.fancybox.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/assets/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.25/fc-3.3.3/datatables.min.js"></script>


    <!-- Main Js -->
    <script src="~/assets/js/main.min.js"></script>
</body>

</html>

GoldenblockAdmin/Views/Shared/_LeftMenu.cshtml
@using Goldenblock.Common;
@using GoldenblockAdmin.Pages;
@using System.Web.Optimization;

<aside>
    <div class="navbar-vertical">
        <div class="navbar-brand-wrapper text-center">
            <a href="" class="navbar-brand fw-bold text-dark">
                골든블락
            </a>
        </div>

        <div class="navbar-vertical-content" data-simplebar>
            <ul class="navbar-vertical-nav list-unstyled">

                <li class="navbar-vertical-item">
                    <a href="#investmentProperty" id="investmentPropertyli" data-toggle="collapse" role="button" class="navbar-vertical-link has-child">
                        <div class="navbar-vertical-icon">
                            <svg width="24" height="24" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M0.0625 31.9375V0.0625H31.9375V31.9375H0.0625Z" stroke="currentColor" stroke-width="0.125" />
                                <path d="M16 20C20.4183 20 24 16.4183 24 12C24 7.58172 20.4183 4 16 4C11.5817 4 8 7.58172 8 12C8 16.4183 11.5817 20 16 20Z" stroke="currentColor" stroke-width="2" stroke-miterlimit="10" />
                                <path d="M3.8736 26.9988C5.10305 24.8708 6.87086 23.1037 8.99945 21.8752C11.128 20.6467 13.5424 20 16.0001 20C18.4578 20 20.8722 20.6468 23.0007 21.8754C25.1293 23.1039 26.8971 24.871 28.1265 26.9991" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </div>
                        투자상품관리
                    </a>

                    <div class="collapse show" id="investmentProperty">

                        <ul class="list-unstyled">
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("ProductInquiry","InvestmentProductManagement")"  id="productInquiry" class="navbar-vertical-link">상품조회</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("InvestmentAttractionList","InvestmentProductManagement")" id="investmentAttractionList"  class="navbar-vertical-link activeOngingInvestment">투자유치리스트</a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="navbar-vertical-item">
                    <a href="#userManagement" id="userManagementli" data-toggle="collapse" role="button" class="navbar-vertical-link activeUserManagement collapsed has-child">
                        <div class="navbar-vertical-icon">
                            <svg width="24" height="24" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M12 19H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M12 15H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M20.0002 5H25C25.2652 5 25.5196 5.10536 25.7071 5.29289C25.8946 5.48043 26 5.73478 26 6V27C26 27.2652 25.8946 27.5196 25.7071 27.7071C25.5196 27.8946 25.2652 28 25 28H7C6.73478 28 6.48043 27.8946 6.29289 27.7071C6.10536 27.5196 6 27.2652 6 27V6C6 5.73478 6.10536 5.48043 6.29289 5.29289C6.48043 5.10536 6.73478 5 7 5H11.9997" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M11 9V8C11 6.67392 11.5268 5.40215 12.4645 4.46447C13.4021 3.52678 14.6739 3 16 3C17.3261 3 18.5979 3.52678 19.5355 4.46447C20.4732 5.40215 21 6.67392 21 8V9H11Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </div>
                        회원관리
                    </a>

                    <div class="collapse showUsersMenu" id="userManagement">

                        <ul class="list-unstyled">
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("UserProfile","MemberManagement")" id="userProfile"  class="navbar-vertical-link activeUsersInfo">회원정보</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("CoinDepositAndWithdrawal","MemberManagement")" id="coinDepositAndWithdrawal"  class="navbar-vertical-link activeDepositWithdrawal">코인입출금</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("CoinTransactionHistory","MemberManagement")" id="coinTransactionHistory"  class="navbar-vertical-link activeTransectionHistory">코인거래 내역</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("CoinStaking","MemberManagement")" id="coinStaking"  class="navbar-vertical-link activeCoinStaking">코인 스테이킹</a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="navbar-vertical-item">
                    <a href="#publicNotification" id="publicNotificationli" data-toggle="collapse" role="button" class="navbar-vertical-link activeNoticeMgt collapsed has-child">
                        <div class="navbar-vertical-icon">
                            <svg width="24" height="24" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3.99927 6.33334V23.6667C3.99927 23.8219 4.03541 23.975 4.10484 24.1139C4.17427 24.2527 4.27507 24.3735 4.39927 24.4667C4.52346 24.5598 4.66764 24.6228 4.82038 24.6505C4.97312 24.6783 5.13023 24.6701 5.27927 24.6267L27.2793 18.21C27.487 18.1494 27.6694 18.0231 27.7993 17.85C27.9291 17.6769 27.9993 17.4664 27.9993 17.25V12.75C27.9993 12.5336 27.9291 12.3231 27.7993 12.15C27.6694 11.9769 27.487 11.8506 27.2793 11.79L5.27927 5.37334C5.13023 5.32987 4.97312 5.32169 4.82038 5.34947C4.66764 5.37724 4.52346 5.44019 4.39927 5.53334C4.27507 5.62648 4.17427 5.74727 4.10484 5.88612C4.03541 6.02498 3.99927 6.17809 3.99927 6.33334V6.33334Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M23 19.4581V24C23 24.2652 22.8946 24.5196 22.7071 24.7071C22.5196 24.8946 22.2652 25 22 25H18C17.7348 25 17.4804 24.8946 17.2929 24.7071C17.1054 24.5196 17 24.2652 17 24V8.79188" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </div>
                        공지사항 관리
                    </a>

                    <div class="collapse showNoticeMgt" id="publicNotification">

                        <ul class="list-unstyled">
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("Notice","NoticeManagement")" id="notice"  class="navbar-vertical-link activeNotice">공지사항</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("Terms","NoticeManagement")" id="terms"  class="navbar-vertical-link activeTerms">약관</a>
                            </li>
                            <li class="navbar-vertical-item">
                                <a href="@Url.Action("Event","NoticeManagement")" id="event"  class="navbar-vertical-link activeEvent">이벤트</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
        </div>


</aside>